server:
  port: 22222
  servlet:
    session:
      timeout: 10
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
  banner:
    charset: UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
    charset: UTF-8
    templateEncoding: UTF-8
    suffix: .ftl
    allow-request-override: false
    content-type: text/html
    template-loader-path:
      classpath: /templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sunjian?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource